"""add incidents

Revision ID: ec2cf41a52d5
Revises: b7c4e920d631
Create Date: 2026-10-05 01:07:23.480301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2cf41a52d5'
down_revision: Union[str, Sequence[str], None] = 'b7c4e920d631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monitor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (status = 'OPEN' AND resolved_at IS NULL)\n            OR\n            (status = 'RESOLVED' AND resolved_at IS NOT NULL)\n            ", name='ck_incidents_resolution'),
    sa.CheckConstraint("status IN ('OPEN', 'RESOLVED')", name='ck_incidents_status'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_monitor_id_started_at', 'incidents', ['monitor_id', 'started_at'], unique=False)
    op.create_index('uq_incidents_open_monitor', 'incidents', ['monitor_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_incidents_open_monitor', table_name='incidents', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index('ix_incidents_monitor_id_started_at', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
